[package]
name = "dto"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
axum_typed_multipart = "0.15.1"
chrono = { version = "0.4.40", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tempfile = "3.18.0"
